from http.server import BaseHTTPRequestHandler
import requests
import json
import traceback

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()

        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }
        
        # ၁။ Access Token တောင်းယူခြင်း[span_1](start_span)[span_1](end_span)
        token_url = "https://cloud-as.ruijienetworks.com/service/api/oauth20/client/access_token?token=d63dss0a81e4415a889ac5b78fsc904a"
        token_payload = json.dumps({
            "appid": "openc3be644fb5dc",
            "secret": "0dea886911864f359497a65f94164518"
        })
        
        try:
            token_res = requests.post(token_url, headers=headers, data=token_payload)
            token_data = token_res.json()
            access_token = token_data.get("accessToken")
            
            if not access_token:
                self.wfile.write(json.dumps({"error": "Token မရရှိပါ။", "details": token_data}).encode('utf-8'))
                return

            # --- ဤနေရာတွင် သင့် Ruijie Cloud ထဲမှ မှန်ကန်သော Group ID (Project ID) ကို တိုက်ရိုက်ထည့်ပါ ---
            group_id = 12482  # <-- သင့်အကောင့်ထဲရှိ Group ID အမှန်ဖြင့် လဲပါ
            
            # ၂။ User Group List ကို တိုက်ရိုက်လှမ်းခေါ်ခြင်း[span_2](start_span)[span_2](end_span)
            user_group_url = f"https://cloud-as.ruijienetworks.com/service/api/intl/usergroup/list/{group_id}?pageIndex=0&pageSize=10&access_token={access_token}"
            ug_res = requests.get(user_group_url, headers=headers)
            ug_data = ug_res.json()
            
            profile_uuid = None
            user_group_id = None
            
            try:
                data_list = ug_data.get("data", [])
                if len(data_list) > 0:
                    profile_uuid = data_list[0].get("authProfileId")
                    user_group_id = data_list[0].get("id")
            except Exception:
                pass

            if not profile_uuid or not user_group_id:
                self.wfile.write(json.dumps({
                    "error": "Profile or User Group ID not found in this Group",
                    "debug_response": ug_data
                }).encode('utf-8'))
                return

            # ၃။ Voucher ထုတ်လုပ်ခြင်း (Generate Voucher API)[span_3](start_span)[span_3](end_span)
            voucher_url = f"https://cloud-as.ruijienetworks.com/service/api/open/auth/voucher/create/{group_id}?access_token={access_token}"
            
            voucher_payload = json.dumps({
                "quantity": 1,
                "profile": str(profile_uuid),
                "userGroupId": int(user_group_id),
                "comment": "AutoGenerated"
            })

            voucher_res = requests.post(voucher_url, headers=headers, data=voucher_payload)
            voucher_data = voucher_res.json()
            
            # အောင်မြင်သော Voucher ရလဒ်ကို ပြသခြင်း[span_4](start_span)[span_4](end_span)
            self.wfile.write(json.dumps(voucher_data).encode('utf-8'))
            
        except Exception as e:
            self.wfile.write(json.dumps({
                "error": "System Error",
                "message": str(e),
                "traceback": traceback.format_exc()
            }).encode('utf-8'))
        
        return
