from http.server import BaseHTTPRequestHandler
import requests
import json
import traceback

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()

        APP_ID = "openc3be644fb5dc"
        SECRET = "0dea886911864f359497a65f94164518"
        BASE_URL = "https://cloud-as.ruijienetworks.com"
        GROUP_ID = "7833000"

        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }
        
        try:
            # ၁။ Access Token တောင်းယူခြင်း[span_0](start_span)[span_0](end_span)
            token_url = f"{BASE_URL}/service/api/oauth20/client/access_token?token=d63dss0a81e4415a889ac5b78fsc904a"
            token_payload = json.dumps({
                "appid": APP_ID,
                "secret": SECRET
            })
            
            token_res = requests.post(token_url, headers=headers, data=token_payload)
            token_data = token_res.json()
            
            if token_res.status_code != 200 or token_data.get("code") != 0:
                self.wfile.write(json.dumps({"error": "Token ရယူရန် မအောင်မြင်ပါ", "details": token_data}).encode('utf-8'))
                return

            access_token = token_data.get("accessToken")

            # ၂။ User Group List ကို လှမ်းခေါ်ပြီး မှန်ကန်သော Profile ID နှင့် User Group ID ကို ရယူခြင်း[span_1](start_span)[span_1](end_span)
            user_group_url = f"{BASE_URL}/service/api/intl/usergroup/list/{GROUP_ID}?pageIndex=0&pageSize=10&access_token={access_token}"
            ug_res = requests.get(user_group_url, headers=headers)
            ug_data = ug_res.json()
            
            profile_uuid = None
            user_group_id = None
            
            try:
                data_list = ug_data.get("data", [])
                if len(data_list) > 0:
                    profile_uuid = data_list[0].get("authProfileId")
                    user_group_id = data_list[0].get("id")
            except Exception:
                pass

            if not profile_uuid or not user_group_id:
                self.wfile.write(json.dumps({
                    "error": "User Group သို့မဟုတ် Profile ရှာမတွေ့ပါ။",
                    "debug_response": ug_data
                }).encode('utf-8'))
                return

            # ၃။ Voucher ထုတ်လုပ်ခြင်း (Generate Voucher API)[span_2](start_span)[span_2](end_span)
            voucher_url = f"{BASE_URL}/service/api/open/auth/voucher/create/{GROUP_ID}?access_token={access_token}"
            
            voucher_payload = json.dumps({
                "quantity": 1,
                "profile": str(profile_uuid),
                "userGroupId": int(user_group_id),
                "comment": "AutoGenerated"
            })

            voucher_res = requests.post(voucher_url, headers=headers, data=voucher_payload)
            voucher_data = voucher_res.json()
            
            # အောင်မြင်သော Voucher ရလဒ်ကို ပြသခြင်း[span_3](start_span)[span_3](end_span)
            self.wfile.write(json.dumps(voucher_data).encode('utf-8'))
            
        except Exception as e:
            self.wfile.write(json.dumps({
                "error": "System Error",
                "message": str(e),
                "traceback": traceback.format_exc()
            }).encode('utf-8'))
        
        return
