from http.server import BaseHTTPRequestHandler
import requests
import json
import traceback

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()

        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }
        
        # ၁။ Access Token တောင်းယူခြင်း
        token_url = "https://cloud-as.ruijienetworks.com/service/api/oauth20/client/access_token?token=d63dss0a81e4415a889ac5b78fsc904a"
        token_payload = json.dumps({
            "appid": "openc3be644fb5dc",
            "secret": "0dea886911864f359497a65f94164518"
        })
        
        try:
            token_res = requests.post(token_url, headers=headers, data=token_payload)
            token_data = token_res.json()
            access_token = token_data.get("accessToken")
            
            if not access_token:
                self.wfile.write(json.dumps({"error": "Token မရရှိပါ။", "details": token_data}).encode('utf-8'))
                return

            # ၂။ Group ID ရယူရန် Network Group List လှမ်းခေါ်ခြင်း
            group_tree_url = f"https://cloud-as.ruijienetworks.com/service/api/group/single/tree?depth=BUILDING&access_token={access_token}"
            group_tree_res = requests.get(group_tree_url, headers=headers)
            group_tree_data = group_tree_res.json()
            
            group_id = None
            try:
                groups_info = group_tree_data.get("groups", {})
                if "subGroups" in groups_info and len(groups_info["subGroups"]) > 0:
                    group_id = groups_info["subGroups"][0]["groupId"]
                else:
                    group_id = groups_info.get("groupId", 0)
            except Exception:
                group_id = 0

            if not group_id:
                group_id = 0

            # ၃။ User Group List (Profile UUID နှင့် User Group ID) ကို ဆွဲထုတ်ခြင်း
            user_group_url = f"https://cloud-as.ruijienetworks.com/service/api/intl/usergroup/list/{group_id}?pageIndex=0&pageSize=10&access_token={access_token}"
            ug_res = requests.get(user_group_url, headers=headers)
            ug_data = ug_res.json()
            
            # အကောင့်ထဲတွင် ရှိပြီးသား ပထမဆုံး User Group နှင့် Profile ID ကို ယူမည်
            profile_uuid = None
            user_group_id = None
            
            try:
                data_list = ug_data.get("data", [])
                if len(data_list) > 0:
                    profile_uuid = data_list[0].get("authProfileId")
                    user_group_id = data_list[0].get("id")
            except Exception:
                pass

            if not profile_uuid or not user_group_id:
                # အကယ်၍ မတွေ့ပါက Error ထုတ်ပြမည်
                self.wfile.write(json.dumps({
                    "error": "User Group or Profile not found",
                    "debug_usergroup_response": ug_data
                }).encode('utf-8'))
                return

            # ၄။ Voucher ထုတ်လုပ်ခြင်း (Generate Voucher API)
            voucher_url = f"https://cloud-as.ruijienetworks.com/service/api/open/auth/voucher/create/{group_id}?access_token={access_token}"
            
            voucher_payload = json.dumps({
                "quantity": 1,
                "profile": str(profile_uuid),
                "userGroupId": int(user_group_id),
                "comment": "AutoGenerated"
            })

            voucher_res = requests.post(voucher_url, headers=headers, data=voucher_payload)
            voucher_data = voucher_res.json()
            
            # အောင်မြင်သော Voucher ရလဒ်ကို ပြသခြင်း
            self.wfile.write(json.dumps(voucher_data).encode('utf-8'))
            
        except Exception as e:
            self.wfile.write(json.dumps({
                "error": "System Error",
                "message": str(e),
                "traceback": traceback.format_exc()
            }).encode('utf-8'))
        
        return
